export const listaDeContatos = [
    {
        nomeContato: 'João',
        empresa: 'Empresa A',
        telefone: '123456789',
        id: 1,
        cnpj: '12345678901234',
        cidade: 'São Paulo',
        situacao: 'ativo',
        tipoPessoa: 'Física',
        dataCadastro: '2024-01-17',
        razaoSocial: 'Nome da Razão Social A',
        uf: 'SP',
        bairro: 'Bairro A',
        cep: '12345-678',
        endereco: 'Rua A, 123',
        email: 'joanderson@gmail.com'
    },
    {
        nomeContato: 'Maria',
        empresa: 'Empresa B',
        telefone: '987654321',
        id: 2,
        cnpj: '98765432109876',
        cidade: 'Rio de Janeiro',
        situacao: 'inativo',
        tipoPessoa: 'Jurídica',
        dataCadastro: '2024-01-17',
        razaoSocial: 'Nome da Razão Social B',
        uf: 'RJ',
        bairro: 'Bairro B',
        cep: '87654-321',
        endereco: 'Avenida B, 456',
        email: 'joanderson@gmail.com'
    },
    {
        nomeContato: 'Carlos',
        empresa: 'Empresa C',
        telefone: '555555555',
        id: 3,
        cnpj: '55555555555555',
        cidade: 'Brasília',
        situacao: 'ativo',
        tipoPessoa: 'Jurídica',
        dataCadastro: '2024-01-17',
        razaoSocial: 'Nome da Razão Social C',
        uf: 'DF',
        bairro: 'Bairro C',
        cep: '55555-555',
        endereco: 'Quadra C, 789',
        email: 'joanderson@gmail.com'
    },
    {
        nomeContato: 'Ana',
        empresa: 'Empresa D',
        telefone: '111111111',
        id: 4,
        cnpj: '11111111111111',
        cidade: 'Salvador',
        situacao: 'inativo',
        tipoPessoa: 'Física',
        dataCadastro: '2024-01-17',
        razaoSocial: 'Nome da Razão Social D',
        uf: 'BA',
        bairro: 'Bairro D',
        cep: '11111-111',
        endereco: 'Praça D, 101',
        email: 'joanderson@gmail.com'
    },
    {
        nomeContato: 'Pedro',
        empresa: 'Empresa E',
        telefone: '222222222',
        id: 5,
        cnpj: '22222222222222',
        cidade: 'Recife',
        situacao: 'ativo',
        tipoPessoa: 'Física',
        dataCadastro: '2024-01-17',
        razaoSocial: 'Nome da Razão Social E',
        uf: 'PE',
        bairro: 'Bairro E',
        cep: '22222-222',
        endereco: 'Rua E, 222',
        email: 'joanderson@gmail.com'
    },
    {
        nomeContato: 'Laura',
        empresa: 'Empresa F',
        telefone: '333333333',
        id: 6,
        cnpj: '33333333333333',
        cidade: 'Fortaleza',
        situacao: 'inativo',
        tipoPessoa: 'Jurídica',
        dataCadastro: '2024-01-17',
        razaoSocial: 'Nome da Razão Social F',
        uf: 'CE',
        bairro: 'Bairro F',
        cep: '33333-333',
        endereco: 'Avenida F, 333',
        email: 'joanderson@gmail.com'
    },
    {
        nomeContato: 'Gabriel',
        empresa: 'Empresa G',
        telefone: '444444444',
        id: 7,
        cnpj: '44444444444444',
        cidade: 'Belém',
        situacao: 'ativo',
        tipoPessoa: 'Física',
        dataCadastro: '2024-01-17',
        razaoSocial: 'Nome da Razão Social G',
        uf: 'PA',
        bairro: 'Bairro G',
        cep: '44444-444',
        endereco: 'Alameda G, 444',
        email: 'joanderson@gmail.com'
    },
    {
        nomeContato: 'Isabela',
        empresa: 'Empresa H',
        telefone: '666666666',
        id: 8,
        cnpj: '66666666666666',
        cidade: 'Manaus',
        situacao: 'inativo',
        tipoPessoa: 'Jurídica',
        dataCadastro: '2024-01-17',
        razaoSocial: 'Nome da Razão Social H',
        uf: 'AM',
        bairro: 'Bairro H',
        cep: '66666-666',
        endereco: 'Travessa H, 666',
        email: 'joanderson@gmail.com'
    },
    {
        nomeContato: 'Fernando',
        empresa: 'Empresa I',
        telefone: '777777777',
        id: 9,
        cnpj: '77777777777777',
        cidade: 'Curitiba',
        situacao: 'ativo',
        tipoPessoa: 'Física',
        dataCadastro: '2024-01-17',
        razaoSocial: 'Nome da Razão Social I',
        uf: 'PR',
        bairro: 'Bairro I',
        cep: '77777-777',
        endereco: 'Rua I, 777',
        email: 'joanderson@gmail.com'
    },
    {
        nomeContato: 'Amanda',
        empresa: 'Empresa J',
        telefone: '999999999',
        id: 10,
        cnpj: '99999999999999',
        cidade: 'Porto Alegre',
        situacao: 'inativo',
        tipoPessoa: 'Jurídica',
        dataCadastro: '2024-01-17',
        razaoSocial: 'Nome da Razão Social J',
        uf: 'RS',
        bairro: 'Bairro J',
        cep: '99999-999',
        endereco: 'Avenida J, 999',
        email: 'joanderson@gmail.com'
    },
];


export const motivos = [
    { id: 1, nome: 'Adesão de Sistema Comercial' },
    { id: 2, nome: 'Dúvidas no Sistema' },
    { id: 3, nome: 'Erro de Sistema' },
    { id: 4, nome: 'Erro de Usuário' },
    { id: 5, nome: 'Financeiro' },
    { id: 6, nome: 'Fora de Expediente' },
    { id: 7, nome: 'Licença de Uso' },
    { id: 8, nome: 'Nova Funcionalidade' },
    { id: 9, nome: 'Ofertas' },
    { id: 10, nome: 'Recorrência (Cliente)' },
    { id: 11, nome: 'Recorrência (Suporte)' },
    { id: 12, nome: 'Reinstalação de Sistema' },
    { id: 13, nome: 'Resolvido pelo Cliente' },
    { id: 14, nome: 'Solicitando Visita' },
    { id: 15, nome: 'Treinamento (In Loco)' },
    { id: 16, nome: 'XML' }
];

// Exemplo de uso:
console.log(motivos.ADESAO_SISTEMA_COMERCIAL); // Saída: Adesão de Sistema Comercial
